ARG source_image
FROM ${source_image}
ENV RAILS_ENV=test
COPY --chown=app:app ./spec /home/app/atos/spec
COPY --chown=app:app ./.rspec /home/app/atos/.rspec
USER root
RUN apk add --no-cache --virtual .build-tools git build-base curl-dev && \
    cd /home/app/atos && \
    bundle install --no-cache --jobs=5 --retry=3 --without=development --with=production test --deployment && \
    apk del .build-tools && \
    chown -R app:app /home/app/atos/vendor/bundle
## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
USER app
CMD ["sh", "-c", "/wait && bundle exec rake db:create db:migrate && bundle exec rspec"]
